### ISSUE TITLE
Deploy the application

### ISSUE THREAD

**Issue by shannonscotta** [mcsp-blue-ocean/quest#16]
Choose a site to host our project, determine why it's best that we use X instead of Y and Z, and then implement X.

google cloud AND render deployment

**Comment by shannonscotta** [comment]
Azure?
Google cloud?

**Comment by AGI-CEO** [comment]
We've  (+ @mitchellnkeo) determined that we will likely strive to deploy on all platforms-- Azure, Google, Render.
We will prioritize Azure and Render as stated in the rough PACE plan.

During evening code review, we intend to do a thorough deployment walkthrough so that all team members gain experience and familiarity with the different cloud platforms. (think hip pocket class)

**Comment by gnprwx** [comment]
So is this good to close now @mitchellnkeo and @AGI-CEO ?

**Comment by mitchellnkeo** [comment]
I think it's good to close. @AGI-CEO you good with it?

**Comment by AGI-CEO** [comment]
I did want to look at the Google cloud deployment at some point next week. That's where my hesitation is at for closing. I was thinking maybe Tuesday or Wednesday next week. 

I'll close this one and open a new ticket next week then so at least ticket name is more accurate to intended outcome
